# Generated by Django 4.2.dev20221118134729 on 2022-11-23 08:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VendorCategory',
            fields=[
                ('vendorCategory', models.AutoField(primary_key=True, serialize=False)),
                ('vendorCategoryName', models.CharField(max_length=30)),
            ],
            options={
                'db_table': 'db_vendor_categories',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('vendorId', models.AutoField(primary_key=True, serialize=False)),
                ('vendorName', models.CharField(max_length=50)),
                ('vendorCategory', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.vendorcategory')),
            ],
            options={
                'db_table': 'db_vendors',
                'ordering': ['vendorId'],
            },
        ),
    ]
